# Don't print a new line at the start of the prompt
add_newline = false

# https://starship.rs/config/#prompt
# Time and directory are rearranged here
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$time\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$directory\
$status\
$shell\
$character"""

# Time module
[time]
use_12hr = true
disabled = false
time_format = "%I:%M %p"
utc_time_offset = -7

# Directory listing
[directory]
truncation_length = 2
fish_style_pwd_dir_length	= 1

# Character before prompt
[character]
success_symbol = "[∴](bold green)"
error_symbol = "[∴](bold red)"
vicmd_symbol = "[❮](bold green)"

# Battery monitor
[[battery.display]]
threshold = 15
style = "bold #ff5555"
[[battery.display]]
threshold = 33
style = "bold #ffb86c"
[[battery.display]]
threshold = 66
style = "bold #f1fa8c"
[[battery.display]]
threshold = 100
style = "bold #50fa7b"

# Make git commit joined with the branch
[git_branch]
# No trailing space in quote
format = "on [$symbol$branch]($style)"

# Show current git commit
[git_commit]
# disabled = false
only_detached = false
# prefix = "@"
# suffix = " "
format = "[@$hash]($style) "

[git_status]
deleted = "🗙"

[username]
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "green"

[java]
style = "red"

[nodejs]
symbol = "⬢ "
